<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>honda_jazz</name>
   <tag></tag>
   <elementGuidId>619c2a37-26cb-4a25-947b-43ceb38e39a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;owner-rental&quot;]/div/div/div[2]/div[4]/div/a[2]/div/div[2]/a[1]/h5[count(. | //*[(text() = 'JAZZ' or . = 'JAZZ')]) = count(//*[(text() = 'JAZZ' or . = 'JAZZ')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;owner-rental&quot;]/div/div/div[2]/div[4]/div/a[2]/div/div[2]/a[1]/h5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JAZZ</value>
   </webElementProperties>
</WebElementEntity>
