<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>harga_end</name>
   <tag></tag>
   <elementGuidId>a6d064c8-82ad-4076-a0fe-e1876f4b24a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/app-root/app-homepage/div[1]/div[2]/div/div/div[1]/div[2]/input[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-root/app-homepage/div[1]/div[2]/div/div/div[1]/div[2]/input[2]</value>
   </webElementProperties>
</WebElementEntity>
