<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_5_PaintingKids</name>
   <tag></tag>
   <elementGuidId>0da7454c-b773-42bf-bf4c-d8bcbcb3411d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;step-1&quot;]/div[1]/div/ul/li[6]</value>
   </webElementProperties>
</WebElementEntity>
