<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_images</name>
   <tag></tag>
   <elementGuidId>9f627ad4-6805-433f-bff2-0a7a78a6ac27</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>images[]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>upload input-first-upload</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>.png, .jpg, .jpeg, .arw, .srf, .sr2, .crw, .cr2, .cr3, .dcs, .dcr, .drf, .k25, .kdc, .erf, .mrw, .nef, .nrw, .pxn, .raf, .raw, .rw2, .srw, .x3f</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;first-upload&quot;)/div[@class=&quot;text-center action-btn&quot;]/span[@class=&quot;fileUpload browse-btn&quot;]/input[@class=&quot;upload input-first-upload&quot;]</value>
   </webElementProperties>
</WebElementEntity>
