<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>94d803d5-128f-417b-89b6-4347f0722ffd</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://jom-demo-backend.stagingapps.net/uploads/product_studio_sub_category_group/15280730660.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tour-catalog-2&quot;)/div[@class=&quot;row masonry-container&quot;]/div[@class=&quot;col-md-4 col-sm-6 item&quot;]/div[@class=&quot;thumbnail thumbnail-relative&quot;]/a[1]/div[@class=&quot;img-bg&quot;]/img[1]</value>
   </webElementProperties>
</WebElementEntity>
