<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnAppCar</name>
   <tag></tag>
   <elementGuidId>2a979e52-eba3-4733-b5cc-3ece805bd525</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;listTable&quot;]/tbody/tr/td[7]/a[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;listTable&quot;]/tbody/tr/td[7]/a[3]</value>
   </webElementProperties>
</WebElementEntity>
