<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dengan_driver</name>
   <tag></tag>
   <elementGuidId>4940986d-50a5-4ff5-a303-85bb4319742e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/app-owner/div[1]/app-price/div/div[2]/form/div[1]/div[1]/div[1]/div/div[1]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-owner/div[1]/app-price/div/div[2]/form/div[1]/div[1]/div[1]/div/div[1]/label</value>
   </webElementProperties>
</WebElementEntity>
