<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>45f4b7da-3426-4c04-863e-023eaf3c997e</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-u</name>
      <type>Main</type>
      <value>image</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://jom-demo-backend.stagingapps.net/uploads/template/15259367891.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jssor_template_5b641b91256a9&quot;)/div[1]/div[@class=&quot;drag-slider-template&quot;]/div[@class=&quot;data-u&quot;]/div[3]/div[@class=&quot;form-group-on-jssor&quot;]/label[1]/div[@class=&quot;box-template order-studio-box&quot;]/img[1]</value>
   </webElementProperties>
</WebElementEntity>
