<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_total_person</name>
   <tag></tag>
   <elementGuidId>efa9f3b3-5f5e-4079-9dc9-784a59558209</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;setting-setup-5b6bae6a5f40f&quot;)/div[@class=&quot;box-panel&quot;]/div[@class=&quot;clearfix&quot;]/form[@id=&quot;form-additional-people&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-4&quot;]/input[@id=&quot;tour-checkout-2&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>id(&quot;setting-setup-5b6bae6a5f40f&quot;)/div[@class=&quot;box-panel&quot;]/div[@class=&quot;clearfix&quot;]/form[@id=&quot;form-additional-people&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-4&quot;]/input[@id=&quot;tour-checkout-2&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>total_person</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tour-checkout-2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2
</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan jumlah orang yang anda inginkan</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;setting-setup-5b6bae6a5f40f&quot;)/div[@class=&quot;box-panel&quot;]/div[@class=&quot;clearfix&quot;]/form[@id=&quot;form-additional-people&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-4&quot;]/input[@id=&quot;tour-checkout-2&quot;]</value>
   </webElementProperties>
</WebElementEntity>
