<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pilih</name>
   <tag></tag>
   <elementGuidId>d2625ac8-e647-4c83-a951-41e614092e77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;template-photo-all&quot;)/div[1]/div[@class=&quot;drag-slider-template&quot;]/div[@class=&quot;data-u&quot;]/div[2]/div[@class=&quot;form-group-on-jssor&quot;]/label[@class=&quot;box-template-label&quot;]/div[@class=&quot;box-template box-template-custom&quot;]/button[@class=&quot;waves-effect waves-light btn-submit btn-gold-effect float-btn btn-trigger-select-photo&quot;][count(. | //button[(text() = 'Pilih' or . = 'Pilih')]) = count(//button[(text() = 'Pilih' or . = 'Pilih')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>waves-effect waves-light btn-submit btn-gold-effect float-btn btn-trigger-select-photo</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;template-photo-all&quot;)/div[1]/div[@class=&quot;drag-slider-template&quot;]/div[@class=&quot;data-u&quot;]/div[2]/div[@class=&quot;form-group-on-jssor&quot;]/label[@class=&quot;box-template-label&quot;]/div[@class=&quot;box-template box-template-custom&quot;]/button[@class=&quot;waves-effect waves-light btn-submit btn-gold-effect float-btn btn-trigger-select-photo&quot;]</value>
   </webElementProperties>
</WebElementEntity>
