<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_pilih_1</name>
   <tag></tag>
   <elementGuidId>814a3f65-c9da-4973-b456-b8fb96086d13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;template-photo-all&quot;]/div/div/div[3]/div[2]/div[1]/label/div/button</value>
   </webElementProperties>
</WebElementEntity>
