<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_batal</name>
   <tag></tag>
   <elementGuidId>519e24a0-0967-4ebf-882a-a763aea03d1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;data-pesanan&quot;]/div[5]/div/div/div[3]/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;data-pesanan&quot;]/div[5]/div/div/div[3]/button[1]</value>
   </webElementProperties>
</WebElementEntity>
