<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_release_manual</name>
   <tag></tag>
   <elementGuidId>a2044123-421b-432b-a072-0905e0aa3288</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;modal-release&quot;]/div/div/div[3]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;modal-release&quot;]/div/div/div[3]/button[2]</value>
   </webElementProperties>
</WebElementEntity>
