<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DETAIL</name>
   <tag></tag>
   <elementGuidId>7aa5f0df-d7bc-443a-bf8e-e987353dc53b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;listTables&quot;]/tbody/tr[1]/td[20]/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;listTables&quot;]/tbody/tr[1]/td[20]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
