<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_2</name>
   <tag></tag>
   <elementGuidId>3ee5317c-96a4-4686-a074-94013526534b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>prod-checkbox8</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;large-print&quot;)/table[@class=&quot;table table-hover no-margin&quot;]/tbody[1]/tr[1]/td[1]/fieldset[@class=&quot;form-group no-border checkbox-reg&quot;]/label[1]</value>
   </webElementProperties>
</WebElementEntity>
