<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ins_iCheck-helper_2</name>
   <tag></tag>
   <elementGuidId>4ba411c0-2ff6-460b-b88a-1c1676d73f7e</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ins</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iCheck-helper</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-weekday&quot;)/div[@class=&quot;iradio_square-blue hover checked&quot;]/ins[@class=&quot;iCheck-helper&quot;]</value>
   </webElementProperties>
</WebElementEntity>
