<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ins_iCheck-helper_3</name>
   <tag></tag>
   <elementGuidId>295240ba-f417-4471-9336-c89789a954c0</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ins</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iCheck-helper</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;production_process_tab&quot;)/div[@class=&quot;col-sm-12 col-md-12 col-lg-12&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-12 col-md-8 col-lg-8&quot;]/label[@class=&quot;checkbox-inline icheck&quot;]/div[@class=&quot;iradio_square-blue disabled&quot;]/ins[@class=&quot;iCheck-helper&quot;]</value>
   </webElementProperties>
</WebElementEntity>
