<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Delete</name>
   <tag></tag>
   <elementGuidId>d80efac2-3715-4638-9479-ab4c857770f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;DataTables_Table_0&quot;]/tbody/tr[1]/td[7]/a[3]/i</value>
   </webElementProperties>
</WebElementEntity>
