<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Makanan</name>
   <tag></tag>
   <elementGuidId>6e75f5a7-6a02-4b33-b3a3-4521116d6e33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;DataTables_Table_0&quot;]/tbody/tr[10]/td[2]</value>
   </webElementProperties>
</WebElementEntity>
