<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Bandung</name>
   <tag></tag>
   <elementGuidId>11320392-c16e-4efa-8029-5840b54280c6</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bandung</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/be-come-owner[1]/div[@class=&quot;container-type-b&quot;]/div[1]/div[@class=&quot;row m-0 mx-xl-5 mb-4&quot;]/div[@class=&quot;col mx-xl-5 p-0&quot;]/div[@class=&quot;mx-xl-5&quot;]/form[@class=&quot;ng-valid ng-dirty ng-touched&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;ng2-auto-complete-wrapper&quot;]/ng2-auto-complete[1]/div[@class=&quot;ng2-auto-complete&quot;]/ul[1]/li[@class=&quot;item&quot;]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
