<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Food_and_Bev</name>
   <tag></tag>
   <elementGuidId>95a6e82d-9011-4708-89f5-af1ca7950ccd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;DataTables_Table_0&quot;]/tbody/tr/td[2]</value>
   </webElementProperties>
</WebElementEntity>
