<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>cc9c0b68-a71d-4d3c-b39b-61a5b0d88835</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>26</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/google-logo.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>26</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-root[1]/app-homepage[1]/app-header-second[1]/div[@class=&quot;header2&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-9&quot;]/a[@class=&quot;mr-5 link-btn dropdown&quot;]/div[@class=&quot;popum dropdown-content&quot;]/div[@class=&quot;pop-login-in&quot;]/div[@class=&quot;top-borer&quot;]/a[@class=&quot;login-by&quot;]/img[1]</value>
   </webElementProperties>
</WebElementEntity>
