<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_pilih_5</name>
   <tag></tag>
   <elementGuidId>f2a22309-b4ae-445b-bb72-e2d482c1e7af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;template-photo-all&quot;]/div/div/div[3]/div[6]/div[1]/label/div/button</value>
   </webElementProperties>
</WebElementEntity>
