<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_1</name>
   <tag></tag>
   <elementGuidId>199857d8-b6db-4078-a876-fd2bb49134ab</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>row</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            1
                                        </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step-1&quot;)/div[@class=&quot;box-order&quot;]/div[@class=&quot;flat-box recapitulation-your-photo no-padding-bottom&quot;]/div[@class=&quot;recap-table edit-advance&quot;]/div[@class=&quot;table-responsive table-modalproduct no-padding-left no-padding-right&quot;]/table[@class=&quot;table product-table summary-table&quot;]/tbody[1]/tr[@class=&quot;print-image-row&quot;]/td[1]</value>
   </webElementProperties>
</WebElementEntity>
