<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>default</name>
   <tag></tag>
   <elementGuidId>82f641f0-52ee-4f97-a1a4-d344e31bc2da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;modal-form&quot;]/div/div/div[2]/form/div[1]/div/div[2]/div[1]/div/div/span/span[1]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
