<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Sequence3</name>
   <tag></tag>
   <elementGuidId>fdd5d77a-92b1-473c-b697-6158a706d609</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;jumlah-pose-88&quot;]/tr[3]/td[7]/div/input</value>
   </webElementProperties>
</WebElementEntity>
